version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - "9229"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/slack_bookshelf
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    tty: true
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - "4551:4551"
    links:
      - server
    environment:
      - DOMAIN=server
      - PORT=3000
      - DEBUG=true

volumes:
  node_modules: {}
